"""added deployment status field to strategy_versions

Revision ID: 13b209ce4101
Revises: 6c9078aa33f9
Create Date: 2025-09-11 09:23:51.408625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b209ce4101'
down_revision: Union[str, Sequence[str], None] = '6c9078aa33f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE strategy_versions
        ADD COLUMN deployment_status VARCHAR;
    """)
    op.execute("""
        UPDATE strategy_versions 
        SET deployment_status = 'not_deployed';
    """)
    op.execute("""
        ALTER TABLE strategy_versions
        ALTER COLUMN deployment_status SET NOT NULL;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_versions', 'deployment_status')
    # ### end Alembic commands ###
