"""added prompt field to strategy versions

Revision ID: 25692fedf2c5
Revises: 27c3e1f0c722
Create Date: 2025-09-06 11:06:02.170914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25692fedf2c5'
down_revision: Union[str, Sequence[str], None] = '27c3e1f0c722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_versions', sa.Column('prompt', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_versions', 'prompt')
    # ### end Alembic commands ###
