"""removed status from strategy versions and replaced with backtest_status

Revision ID: 27c3e1f0c722
Revises: a99604759896
Create Date: 2025-09-05 23:51:08.285299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c3e1f0c722'
down_revision: Union[str, Sequence[str], None] = 'a99604759896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_versions', sa.Column('backtest_status', sa.String(), nullable=False))
    op.drop_column('strategy_versions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_versions', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('strategy_versions', 'backtest_status')
    # ### end Alembic commands ###
