"""add instruments field to backtests

Revision ID: 4978c05bff9a
Revises: fde63570e342
Create Date: 2025-09-14 21:02:08.902385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4978c05bff9a'
down_revision: Union[str, Sequence[str], None] = 'fde63570e342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtests', sa.Column('instrument', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtests', 'instrument')
    # ### end Alembic commands ###
