"""added instruments to deployments

Revision ID: 680d662545d3
Revises: 1a960954b35c
Create Date: 2025-09-12 16:59:59.705775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680d662545d3'
down_revision: Union[str, Sequence[str], None] = '1a960954b35c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('instrument', sa.String(), nullable=False))
    op.add_column('positions', sa.Column('extras', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'extras')
    op.drop_column('deployments', 'instrument')
    # ### end Alembic commands ###
