"""added status field to strategy versions

Revision ID: 6c9078aa33f9
Revises: 25692fedf2c5
Create Date: 2025-09-06 11:16:50.193812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9078aa33f9'
down_revision: Union[str, Sequence[str], None] = '25692fedf2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_versions', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_versions', 'status')
    # ### end Alembic commands ###
