"""added reason field to deployments table

Revision ID: ab50ab9c48f0
Revises: 680d662545d3
Create Date: 2025-09-13 00:01:00.420594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab50ab9c48f0'
down_revision: Union[str, Sequence[str], None] = '680d662545d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'reason')
    # ### end Alembic commands ###
