"""added new fields to positions

Revision ID: e40cf301c9e5
Revises: 13b209ce4101
Create Date: 2025-09-11 11:35:55.385666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40cf301c9e5'
down_revision: Union[str, Sequence[str], None] = '13b209ce4101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('instrument', sa.String(), nullable=False))
    op.add_column('positions', sa.Column('side', sa.String(), nullable=False))
    op.add_column('positions', sa.Column('order_type', sa.String(), nullable=False))
    op.add_column('positions', sa.Column('starting_amount', sa.Float(), nullable=False))
    op.add_column('positions', sa.Column('current_amount', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('limit_price', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('stop_price', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('tp_price', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('sl_price', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('realised_pnl', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('unrealised_pnl', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('positions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('positions', sa.Column('close_price', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('positions', 'position_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('positions', 'timestamp')
    op.drop_column('positions', 'size')
    op.drop_column('positions', 'entry_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('positions', sa.Column('size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('positions', sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('positions', 'position_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('positions', 'closed_at')
    op.drop_column('positions', 'close_price')
    op.drop_column('positions', 'created_at')
    op.drop_column('positions', 'status')
    op.drop_column('positions', 'unrealised_pnl')
    op.drop_column('positions', 'realised_pnl')
    op.drop_column('positions', 'sl_price')
    op.drop_column('positions', 'tp_price')
    op.drop_column('positions', 'stop_price')
    op.drop_column('positions', 'limit_price')
    op.drop_column('positions', 'price')
    op.drop_column('positions', 'current_amount')
    op.drop_column('positions', 'starting_amount')
    op.drop_column('positions', 'order_type')
    op.drop_column('positions', 'side')
    op.drop_column('positions', 'instrument')
    # ### end Alembic commands ###
