[project]
name = "strat-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "metatrader5>=5.0.5200",
    "pandas>=2.3.2",
]
